global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: "metricsapp"
    static_configs:
      - targets: ["host.docker.internal:7431", "host.docker.internal:5498"] # hard-coded port matches launchSettings.json
    tls_config:
      insecure_skip_verify: true
